echo "james:: Today you have to work and you had shift at 10:00 to 7:00"
echo "shan:: Sure i will be on time james"
echo "james:: that's okay shan"
echo "shan:: james if you dont mind can i do 9:30 to 6:30 because i had train at 6:50"
echo "james:: ofcourse you can do shan. it's not a problem"
echo "shan:: thanks james"
